using MixVideo.Common.BaseRepository.BaseCommandGenericRepository;

namespace MixVideo.Moduls.Comment.Repository.CommandRepository;

public interface ICommentCommandRepository:ICommandGenericRepository<Comment>;